#server
server:
  port: 8080

#DB
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/haruhandal
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      leak-detection-threshold: 300000


# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haruhandal.dto
  configuration.map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    web: DEBUG


springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
